WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Index page retrieved with post count of <built-in method count of list object at 0x000001F9B3BDDE88>
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:21:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:21:55] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Index page retrieved with post count of <built-in method count of list object at 0x000001F9B545DCC8>
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:21:58] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:21:58] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Index page retrieved with post count of <built-in method count of list object at 0x000001F9B546E488>
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:22:00] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:22:00] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 33, in index
    app.logger.info('Index page retrieved with post count of '+posts.count)
TypeError: can only concatenate str (not "builtin_function_or_method") to str
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:43:53] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Index page retrieved with post count of <built-in method count of list object at 0x000001FD86C1DF48>
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:44:55] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:44:55] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 33, in index
    app.logger.info('Index page retrieved with post count of '+ str(posts.count()))
TypeError: count() takes exactly one argument (0 given)
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:45:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 33, in index
    app.logger.info(f'Index page retrieved with post count of {posts.count()}')
TypeError: count() takes exactly one argument (0 given)
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:47:28] "[35m[1mGET / HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Index page retrieved with post count of 6
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:48:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:48:34] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Health check endpoint invoked 
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:48:47] "GET /healthz HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post.Title +' Retrieved!')
AttributeError: 'sqlite3.Row' object has no attribute 'Title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:49:56] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /100 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post.Title +' Retrieved!')
AttributeError: 'NoneType' object has no attribute 'Title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 17:50:01] "[35m[1mGET /100 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /100 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post.Title +' Retrieved!')
AttributeError: 'NoneType' object has no attribute 'Title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:05:09] "[35m[1mGET /100 HTTP/1.1[0m" 500 -
INFO:app:Index page retrieved with post count of 6
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:05:16] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:05:16] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post.Title +' Retrieved!')
AttributeError: 'sqlite3.Row' object has no attribute 'Title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:05:33] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post.title +' Retrieved!')
AttributeError: 'sqlite3.Row' object has no attribute 'title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:07:02] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Article 2020 CNCF Annual Report Retrieved!
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 66, in post
    app.logger.info(f'post {post_id} and {post.title} retrieved')
AttributeError: 'sqlite3.Row' object has no attribute 'title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:07:43] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
INFO:app:Article 2020 CNCF Annual Report Retrieved!
ERROR:app:Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 66, in post
    app.logger.info(f'post {post_id} and {post.title} retrieved')
AttributeError: 'sqlite3.Row' object has no attribute 'title'
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:07:44] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Article 2020 CNCF Annual Report Retrieved!
INFO:app:post 1 and 2020 CNCF Annual Report retrieved
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:09:07] "GET /1 HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:09:07] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
ERROR:app:Exception on /100 [GET]
Traceback (most recent call last):
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\engmu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 61, in post
    post = get_post(post_id)
  File "app.py", line 20, in get_post
    app.logger.info('Article ' + post['title'] +' Retrieved!')
TypeError: 'NoneType' object is not subscriptable
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:09:11] "[35m[1mGET /100 HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Article with id 100 Not found
INFO:app:A non-existing article with id 100 is accessed and a 404 page is returned
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:13:45] "[33mGET /100 HTTP/1.1[0m" 404 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:13:45] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:About endpoint invoked 
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:14:08] "GET /about HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:14:08] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://10.99.14.49:3111/ (Press CTRL+C to quit)
INFO:app:Creation endpoint retrieved for GET
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:11] "GET /create HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:11] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Creation of article is failed due to missing title 
INFO:app:Creation endpoint retrieved for GET
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:19] "POST /create HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:19] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:Creation of article is failed due to missing title 
INFO:app:Creation endpoint retrieved for GET
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:22] "POST /create HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:22] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:app:A new article is created, with title   and content dsfsfsdf Successfully created 
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:31] "[32mPOST /create HTTP/1.1[0m" 302 -
INFO:app:Index page retrieved with post count of 7
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:31] "GET / HTTP/1.1" 200 -
INFO:werkzeug:10.99.14.49 - - [16/Nov/2022 18:15:31] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
